// Enums shared across frontend and backend

export enum UserRole {
  REVIEWER = 'REVIEWER',
  ADMIN = 'ADMIN',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum DocumentStatus {
  UPLOADED = 'UPLOADED',
  EXTRACTING = 'EXTRACTING',
  EXTRACTED = 'EXTRACTED',
  EXTRACTION_FAILED = 'EXTRACTION_FAILED',
}

export enum AnalysisStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum VerificationStatus {
  VERIFIED = 'VERIFIED',
  PARTIAL_MATCH = 'PARTIAL_MATCH',
  NOT_FOUND = 'NOT_FOUND',
  MISMATCH = 'MISMATCH',
  ALERT = 'ALERT',
  NOT_APPLICABLE = 'NOT_APPLICABLE',
  ERROR = 'ERROR',
}

export enum SignalSeverity {
  CRITICAL = 'CRITICAL',
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW',
}

export enum ReviewPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum ReviewDecision {
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  NEEDS_MORE_REVIEW = 'NEEDS_MORE_REVIEW',
}

export enum SupportLevel {
  SUPPORTED = 'SUPPORTED',
  PARTIAL = 'PARTIAL',
  UNSUPPORTED = 'UNSUPPORTED',
  PENDING_REVIEW = 'PENDING_REVIEW',
}

export enum DataTrustLevel {
  VERIFIED = 'VERIFIED',
  DETECTED = 'DETECTED',
  AI_INTERPRETED = 'AI_INTERPRETED',
  PENDING_REVIEW = 'PENDING_REVIEW',
  HUMAN_DECISION = 'HUMAN_DECISION',
}

export enum AuditAction {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  LOGIN_FAILED = 'LOGIN_FAILED',
  DOCUMENT_UPLOADED = 'DOCUMENT_UPLOADED',
  PAPER_ANALYSIS_STARTED = 'PAPER_ANALYSIS_STARTED',
  PAPER_ANALYSIS_COMPLETED = 'PAPER_ANALYSIS_COMPLETED',
  PAPER_ANALYSIS_FAILED = 'PAPER_ANALYSIS_FAILED',
  REPORT_VIEWED = 'REPORT_VIEWED',
  EVIDENCE_VIEWED = 'EVIDENCE_VIEWED',
  REVIEW_CREATED = 'REVIEW_CREATED',
  REVIEW_UPDATED = 'REVIEW_UPDATED',
  USER_CREATED = 'USER_CREATED',
  USER_DEACTIVATED = 'USER_DEACTIVATED',
}
